### ISSUE TITLE
Verify header signature in blobs and data columns during backfill

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#7305]
During backfill the only verification we do is of the block's signatures:

https://github.com/sigp/lighthouse/blob/d96b73152e0e4bcedb8e747016ba8070029db50d/beacon_node/beacon_chain/src/historical_blocks.rs#L205-L213

This does not cover the blobs or data columns, which could be mismatched/invalid.

For blobs we should check:

- [x] KZG inclusion proof (already checked by the network crate: https://github.com/sigp/lighthouse/blob/d96b73152e0e4bcedb8e747016ba8070029db50d/beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs#L36).
- [x] Blob data matches the KZG commitment: TODO (verify KZG proof).
- [ ] Signature in the blob's block header matches the block's signature (equality check is fine).

Similarly for data columns.

**Comment by michaelsproul** [comment]
Cheers to @dapplion for raising this!

**Comment by SunnysidedJ** [comment]
Hi @michaelsproul, can I work on this?

**Comment by michaelsproul** [comment]
@SunnysidedJ yes that would be great, thanks!

**Comment by dapplion** [comment]
@SunnysidedJ I'm also working on it in a separate branch. Feel free to copy the code if you like the approach. I'm keen to fix this issue before merging my branch to reduce the diff https://github.com/sigp/lighthouse/pull/7352

verify signatures during range sync: https://github.com/sigp/lighthouse/pull/7352/files#diff-040e5811a1138cc99780af10517d4288761762d1bc610c719390db564eac524cR640-R664

verify signatures during backfill sync: https://github.com/sigp/lighthouse/pull/7352/files#diff-394c4b63116221e5cd8344f6f7046e7f6a02bc8c438da392c990e4c27802b6cfR127-R166

**Comment by SunnysidedJ** [comment]
> [@SunnysidedJ](https://github.com/SunnysidedJ) I'm also working on it in a separate branch. Feel free to copy the code if you like the approach. I'm keen to fix this issue before merging my branch to reduce the diff [#7352](https://github.com/sigp/lighthouse/pull/7352)
> 
> verify signatures during range sync: https://github.com/sigp/lighthouse/pull/7352/files#diff-040e5811a1138cc99780af10517d4288761762d1bc610c719390db564eac524cR640-R664
> 
> verify signatures during backfill sync: https://github.com/sigp/lighthouse/pull/7352/files#diff-394c4b63116221e5cd8344f6f7046e7f6a02bc8c438da392c990e4c27802b6cfR127-R166

Hi @dapplion, thank you for carefully checking the open issues and letting me know about this. I didn't know you've been working on this. I've been working on this over the Easter as well and was failing to test it as described in the draft PR that I just pushed with the work so far #7353. I will align and take the code changes ASAP so that we don't have much diffs and your changes can go in quickly.

I also left the test part as a comment, but wondering how did you test it under Deneb and Fulu setting. The test function testing the backfill works for pre-Deneb but fails for Deneb and beyond when you enable it. If you run it without fork name environment variables, the test doesn't generate blob and data column sidecars. So, I couldn't verify my changes. Please let me know if you have a better idea to test this!

**Comment by dapplion** [comment]
@SunnysidedJ changes look good on your end, what I'm adding on my branch is also tracking _which_ columns are invalid so we can attribute fault to the right peers

I didn't got to test my changes

**Comment by SunnysidedJ** [comment]
@dapplion I've just raised mine as Full PR for review. I tried to minimize conflicts as much as possible. Please find the details here: https://github.com/sigp/lighthouse/pull/7353#issuecomment-2841947506

**Comment by jimmygchen** [comment]
I've updated the issue description as we're verifying KZG during backfill here

https://github.com/sigp/lighthouse/blob/40c2fd5ff4215bcc5c2eed00dcb40dedd6bcc88b/beacon_node/beacon_chain/src/data_availability_checker.rs#L421-L456

#7352 never got merged into `unstable`, so this issue is still outstanding.

**Comment by jimmygchen** [comment]
We already verify the block signature here
https://github.com/sigp/lighthouse/blob/522bd9e9c6ac167f2231525e937c9ebbcb86cf6e/beacon_node/beacon_chain/src/historical_blocks.rs#L224

So i think we could just verify the blob / data column 's block header signature matches the block signature in block coupling.
